services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      - "DOZZLE_USERNAME=admin"
      - "DOZZLE_PASSWORD=admin"
      # - "DOZZLE_FILTER=name=redis"
      - "DOZZLE_BASE=/dozzle"
      - "DOZZLE_NO_ANALYTICS=true"
      - "DOZZLE_ADDR=:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=lan"
      - "traefik.http.routers.dozzle.entrypoints=webhttp"
      - "traefik.http.routers.dozzle.rule=Host(`example.co`)"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.tls.certresolver=letsenc"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8081"
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  lan:
    external: true
