services:
  traefik:
    image: traefik:v2.11.0
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      # - "--entrypoints.http.http.redirections.entrypoint.to=https"
      # - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--log=true"

  dozzle:
    image: amir20/dozzle:v6.4.2
    container_name: dozzle
    environment:
      - "DOZZLE_AUTH_PROVIDER=simple"
      - "DOZZLE_FILTER=name=slow_query"
      - "DOZZLE_BASE=/dozzle"
      - "DOZZLE_ENABLE_ACTIONS=false"
      - "DOZZLE_NO_ANALYTICS=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./users.yml:/data/users.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.entrypoints=http"
      - "traefik.http.routers.dozzle.rule=Host(`example.com`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

  slow_query:
    image: alpine:3.19.1
    container_name: slow_query
    restart: unless-stopped
    network_mode: none
    volumes:
      - ./slow_query.log:/var/log/stream.log
    command:
      # - tail -n 200 /var/log/stream.log > /var/log/stream.log.tmp && mv /var/log/stream.log.tmp /var/log/stream.log
      - tail
      - -f
      - /var/log/stream.log
